name: Build Debug Build

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - github-actions

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        fail-fast: false

    steps:
    - uses: actions/checkout@v2

    - name: Cache Dependencies
      id: cache-dependencies
      uses: actions/cache@v2
      with:
        path: | 
          node_modules
          src-tauri/target
          ~/.cargo
        key: ${{ runner.os }}-dependencies-${{ hashFiles('src-tauri/Cargo.lock') }}-${{ hashFiles('yarn.lock') }}
        restore_keys: |
          ${{ runner.os }}-dependencies-

    - name: Use Node.js 16
      uses: actions/setup-node@v1
      with:
        node-version: 16

    - name: Install Tauri
      run: cargo install tauri-cli --version ^1.0.0-beta

    - name: Install Angular CLI
      run: npm install -g @angular/cli

    - name: Install yarn
      run: npm install -g yarn

    - name: Install dependencies
      run: yarn install

    - name: Build project
      run: cargo tauri build --debug

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: mediarepo-ui-{{ matrix.os }}
        path: |
          src-tauri/release/bundle/*
          src-tauri/release/mediarepo-ui*