[package]
name = "mediarepo-socket"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.130"
tracing = "0.1.29"

[dependencies.mediarepo-core]
path = "../mediarepo-core"

[dependencies.mediarepo-model]
path = "../mediarepo-model"

[dependencies.tokio]
version = "1.12.0"
features = ["net"]

[dependencies.chrono]
version = "0.4.19"
features = ["serde"]

[dependencies.tracing-futures]
version = "0.2.5"
features = ["tokio-executor"]