[package]
name = "mediarepo-socket"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rmp-ipc = "0.4.0"

[dependencies.tokio]
version = "1.12.0"
features = ["net"]