title: mediarepo
email: me@trivernis.net
description: >- 
  Mediarepo is a tool for managing media files. It works similar to image boards
  (boorus) as it allows one to assign tags to media entries and search for entries by using those tags.
baseurl: ""
url: "https://mediarepo.trivernis.dev"
github_username:  Trivernis
# Build settings
plugins:
  - jekyll-feed

collections:
  docs:
    output: true
    sort_by: sort_key

kramdown:
  syntax_highlighter: rouge
  line_numbers: true


badges:
  - img: https://img.shields.io/github/v/release/trivernis/mediarepo?include_prereleases&style=for-the-badge
    href: https://github.com/Trivernis/mediarepo/releases
  - img: https://img.shields.io/aur/version/mediarepo?style=for-the-badge
    href: https://aur.archlinux.org/packages/mediarepo
  - img: https://img.shields.io/github/workflow/status/trivernis/mediarepo/Build%20and%20test?style=for-the-badge
    href: https://github.com/Trivernis/mediarepo/actions/workflows/build.yml
  - img: https://img.shields.io/aur/license/mediarepo?style=for-the-badge
    href: https://github.com/Trivernis/mediarepo/blob/main/LICENSE

urls:
  releases: https://github.com/Trivernis/mediarepo/releases