[package]
name = "mediarepo-api"
version = "0.1.0"
edition = "2018"
license = "gpl-3"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tracing = "0.1.29"
thiserror = "1.0.30"
chrono = "0.4.19"
rmp-ipc = {version = "0.7.2", optional=true}
tauri = {version = "1.0.0-beta.8", optional=true}

[dependencies.serde]
version = "1.0.130"
features = ["serde_derive"]

[features]
tauri-plugin = ["tauri", "rmp-ipc"]