[package]
name = "mediarepo-api"
version = "0.1.0"
edition = "2018"
license = "gpl-3"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tracing = "0.1.29"
thiserror = "1.0.30"
async-trait = {version = "0.1.51", optional=true}
rmp-ipc = {version = "0.7.2", optional=true}
parking_lot = {version="0.11.2", optional=true}
serde_json = {version="1.0.68", optional=true}
directories = {version="4.0.1", optional=true}

[dependencies.serde]
version = "1.0.130"
features = ["serde_derive"]

[dependencies.chrono]
version = "0.4.19"
features = ["serde"]

[dependencies.tauri]
version = "1.0.0-beta.8"
optional=true
default-features = false
features = []

[dependencies.tokio]
version = "1.12.0"
optional = true
features = ["sync", "fs"]

[dependencies.toml]
version = "0.5.8"
optional = true

[features]
tauri-plugin = ["client-api","tauri", "rmp-ipc", "parking_lot", "serde_json"]
client-api = ["rmp-ipc", "async-trait"]