[package]
name = "app"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
license = ""
repository = ""
default-run = "app"
edition = "2018"
build = "src/build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.0.0-beta.4" }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "1.0.0-beta.8", features = ["api-all"] }
rmp-ipc = "0.4.3"
thiserror = "1.0.30"
directories = "4.0.1"
toml = "0.5.8"
typemap_rev = "0.1.5"

[dependencies.tokio]
version = "1.12.0"
features = ["fs", "io-std", "io-util"]

[dependencies.mediarepo]
git = "https://github.com/Trivernis/mediarepo-daemon"
rev = "57308089d58706ee1438f6b55d53691e9e08ce6b"
features = ["library"]
default-features=false

[features]
default = [ "custom-protocol" ]
custom-protocol = [ "tauri/custom-protocol" ]
