[package]
name = "app"
version = "0.1.0"
description = "A Tauri App"
authors = [ "you" ]
license = ""
repository = ""
default-run = "app"
edition = "2018"
build = "src/build.rs"

[build-dependencies]
tauri-build = { version = "1.0.0-beta.4" }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = [ "derive" ] }
tauri = { version = "1.0.0-beta.8", features = ["dialog-all", "path-all"] }
thiserror = "1.0.30"
typemap_rev = "0.1.5"

  [dependencies.tracing-subscriber]
  version = "0.3.0"
  features = [ "env-filter" ]

  [dependencies.mediarepo-api]
  git = "https://github.com/Trivernis/mediarepo-api.git"
  rev = "16b892eab0b3446198601a8f5829d0bd54d2efdf"
  features = [ "tauri-plugin" ]

[features]
default = [ "custom-protocol" ]
custom-protocol = [ "tauri/custom-protocol" ]
