[package]
name = "mediarepo"
version = "0.1.0"
edition = "2018"
license = "gpl-3"
repository = "https://github.com/Trivernis/mediarepo-daemon"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[[bin]]
name = "mediarepo"
path = "src/main.rs"

[dependencies]
tracing = "0.1.29"
toml = "0.5.8"
structopt ="0.3.23"
glob = "0.3.0"
log = "0.4.14"
tracing-flame = "0.1.0"
tracing-appender = "0.2.0"
num-integer = "0.1.44"

[dependencies.mediarepo-core]
path = "./mediarepo-core"

[dependencies.mediarepo-model]
path = "./mediarepo-model"

[dependencies.mediarepo-socket]
path = "./mediarepo-socket"

[dependencies.tokio]
version = "1.12.0"
features = ["macros", "rt-multi-thread", "io-std", "io-util"]

[dependencies.tracing-subscriber]
version="0.2.3"
features = ["env-filter"]