[package]
name = "mediarepo"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[[bin]]
name = "mediarepo"
path = "src/main.rs"

[lib]
name = "mediarepo"
crate-type = ["lib"]

[dependencies]
toml = {version = "0.5.8", optional=true}
structopt = {version="0.3.23", optional=true}
env_logger = "0.9.0"
log = "0.4.14"

[dependencies.mediarepo-core]
path = "./mediarepo-core"

[dependencies.mediarepo-model]
path = "./mediarepo-model"
optional=true

[dependencies.mediarepo-socket]
path = "./mediarepo-socket"
optional=true

[dependencies.tokio]
version = "1.12.0"
features = ["macros", "rt-multi-thread", "io-std", "io-util"]

[features]
default = ["runtime"]
runtime = ["toml", "structopt", "mediarepo-model", "mediarepo-socket"]
library = ["mediarepo-socket"]