[package]
name = "mediarepo-core"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.29"
multihash = "0.15.0"
multibase = "0.9.1"
base64 = "0.13.0"
toml = "0.5.8"
serde = "1.0.130"
typemap_rev = "0.1.5"
futures = "0.3.17"
itertools = "0.10.1"
glob = "0.3.0"

[dependencies.thumbnailer]
version = "0.2.3"
default-features = false

[dependencies.sea-orm]
version = "0.3.2"
default-features = false

[dependencies.sqlx]
version = "0.5.9"
default-features = false
features = ["migrate"]

[dependencies.tokio]
version = "1.12.0"
features = ["fs", "io-util", "io-std"]

[dependencies.mediarepo-api]
git = "https://github.com/Trivernis/mediarepo-api.git"
rev = "9599020726eb9db47b9be7a6c41c2942a477ba09"
features = ["bromine"]

[features]
default = []
ffmpeg = ["thumbnailer/ffmpeg"]