[package]
name = "mediarepo-core"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.29"
multihash = "0.15.0"
multibase = "0.9.1"
base64 = "0.13.0"
toml = "0.5.8"
serde = "1.0.130"
rmp-ipc = "0.11.0"
typemap_rev = "0.1.5"
futures = "0.3.17"
thumbnailer = "0.2.1"
itertools = "0.10.1"
glob = "0.3.0"

[dependencies.sea-orm]
version = "0.3.2"
default-features = false

[dependencies.sqlx]
version = "0.5.9"
default-features = false
features = ["migrate"]

[dependencies.tokio]
version = "1.12.0"
features = ["fs", "io-util", "io-std"]