[package]
name = "mediarepo-core"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.29"
multihash = "0.15.0"
multibase = "0.9.1"
base64 = "0.13.0"

[dependencies.sea-orm]
default-features = false

[dependencies.sqlx]
default-features = false
features = ["migrate"]

[dependencies.tokio]
version = "1.12.0"
features = ["fs", "io-util", "io-std"]