name: Run checks on all projects

on:
  push:
    branches: [ main, develop, gh-actions ]
  pull_request:
    branches: [ main, develop ]

env:
  CARGO_TERM_COLOR: always

jobs:
  
  build:

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        if: ${{ !env.ACT }}

      - name: Install OS-specific dependencies
        uses: knicknic/os-specific-run@v1.0.3
        with:
          linux: |
            sudo apt-get update
            DEBIAN_FRONTEND=noninteractive sudo apt-get install libwebkit2gtk-4.0-dev libgtk-3-dev libappindicator3-dev -y

      - name: Check api
        working-directory: mediarepo-api
        run: cargo check --all-features

      - name: Check daemon
        working-directory: mediarepo-daemon
        run: cargo check --no-default-features

      - name: Check ui backend
        working-directory: mediarepo-ui/src-tauri
        run: cargo check

      - name: Install UI dependencies
        working-directory: mediarepo-ui
        run: |
            npm i -g yarn
            npm i -g @angular/cli
            yarn install

      - name: Lint ui frontend
        working-directory: mediarepo-ui
        run: yarn lint