name: Create pre-release

on:
  push:
    branches:
      - "master"
  jobs:
    pre-release:
      name: Pre Release
      runs-on: ubuntu-latest
    steps:
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: latest
          prerelease: true
          title: Latest Pre-Release
          files: |
            LICENSE